sources:
  spotify: src.sources.spotify.source::SpotifySource
  setlists: src.sources.setlist_fm.source::SetlistSource

artist_name: Foo Fighters
spotify_artist_id: 7jy3rLJdDQY21OgRLCZ9sD
setlist_fm_mbid: 67f66c07-6e61-4026-ade5-7e782fad3a5d

spotify_allowed_albums:
  - 1FyNZvJ6MHO01kl3ySMPdc
  - 6KMkuqIwKkwUhUYRPL6dUc
  - 2qwN15acAl3sm3Idce5vK9
  - 5lnQLEUiVDkLbFJHXHQu9m
  - 3ilXDEG0xiajK8AbqboeJz
  - 2eprpJCYbCbPZRKVGIEJxZ
  - 28q2N44ocJECgf8sbHEDfY
  - 30ly6F6Xl0TKmyBCU50Khv
  - 4EnNuo8fG7dMoxMefbApRY
  - 1zQ6F8gMagKcPL4SoA80cx
